version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: 
      DATABASE_HOST: 
      DATABASE_PORT: 
      DATABASE_USERNAME: 
      DATABASE_PASSWORD: 
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'