version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/src/app
    envrionment:
      NODE_ENV: development
      SERVICE_URL: http://directus:8055/graphql
    restart: on-failure

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, Directus images writes uploads to /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
    environment:
      KEY:
      SECRET:

      DB_CLIENT: "mysql"
      DB_HOST:
      DB_PORT:
      DB_DATABASE:
      DB_USER:
      DB_PASSWORD:

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"
    restart: on-failure
